trigger:  
    - main
pool:
  vmImage: 'ubuntu-latest'

steps:
    - script: |
        git --version
        echo "checked git version"
        docker --version
        echo "checked docker version"
        docker pull nginx:latest
        docker images
        echo "pulled nginx image and listed images"
        
      displayName: 'Tools checked and nginx image pulled'
      
